### ISSUE TITLE
`read_all` attribute

### ISSUE THREAD

**Issue by Ayrx** [sharksforarms/deku#230]
Currently there are the `count`, `bytes_read`, `bits_read` and `until` attributes you can apply to a `Vec` to tell deku how much to read.

A `read_all` (name undecided) attribute that tells deku to parse till the end of the input would be very handy and could be used to avoid some ugly math in the `bytes_read` attribute.

**Comment by dullbananas** [comment]
You don't need bytes_read

```
#[deku(until = "|_| false")]
```

**Comment by mmun** [comment]
It seems like `bits_read = "deku::rest.len()"` mostly works except that it cannot handle an empty array.

**Comment by duskmoon314** [comment]
The new implementation based on reader no longer supports `deku::rest`. Currently, I cannot find a way to read all remaining bytes to a `Vec`.

I think adding a `read_all` attribute lets `reader_vec_with_predicate` check `reader.end()` instead of `predicate` can solve the problem. I hope @wcampbell0x2a can share some ideas.

**Comment by wcampbell0x2a** [comment]
Hey @duskmoon314, does https://github.com/sharksforarms/deku/pull/387 solve your use case?
